name: Public Npm

on:
  push:
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN:  ${{ secrets.NPM_AUTH_TOKEN }}
